### ISSUE TITLE
Great work! Does it also exist for Python?

### ISSUE THREAD

**Issue by deemeetree** [JohnCoene/sigmajs#10]
Super nice realization! Do you know if something like this also exists for Python? As far as I know R is not that different from Python, so I wonder how difficult it would be to port what you wrote to Python as well... What do you think?

**Comment by JohnCoene** [comment]
Thanks! I don't know that this is feasible in Python, this relies on htmlwidgets: I don't think Python has the equivalent though I might be wrong.

**Comment by csaladenes** [comment]
If you render html, you could potentially pass that into a Ipython [embed]((https://stackoverflow.com/questions/25698448/how-to-embed-html-into-ipython-output).

Or more recently, the trend is to create JupyterLab [extensions](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html) which allow you to do that automatically.

The tricky part is that if you do not want to pass the entire data, then you need to a run small server, like `python -m http.server` or so in the background, then embed `localhost:8000`. Might look into this when i have the time.
