### ISSUE TITLE
version of sigma.js 

### ISSUE THREAD

**Issue by rajatsadh24** [JohnCoene/sigmajs#11]
is it 1.2.1 or v2 alpha20

**Comment by JohnCoene** [comment]
It is `1.2.1` as far as I can remember. Did you come across any issue?

**Comment by i18rajats** [comment]
Actually, I want to work on sigma.js 2.0.0 alpha20 but the developer has not yet provided the documentation and even I am unable to run the examples provided in sigma.js v2 repositories.

**Comment by JohnCoene** [comment]
Where can I find that? To the best of my knowledge sigma.js has not seen a commit in over year.
