### ISSUE TITLE
Highlighting neighbors proxy doesn't work

### ISSUE THREAD

**Issue by aprativa** [JohnCoene/sigmajs#12]
Hey,

The title explains the issue. While the `sg_neighbours()` function works fine, the  `sg_neighbours_p()` doesn't. When I try to highlight the nodes, there's no reactivity.

**Comment by JohnCoene** [comment]
Indeed, thank you for reporting this. I will look into it.

**Comment by sgrubsmyon** [comment]
Hi, I found how to fix this issue and it's included in PR #19.
