### ISSUE TITLE
Way to define a layout

### ISSUE THREAD

**Issue by shashj** [JohnCoene/sigmajs#13]
Is there a way to define the coordinates of the layout and pass it to sg_layout function?

**Comment by JohnCoene** [comment]
So `sg_layout` is a helper function to which you can pass any `igraph::layout_*` function, e.g.: `igraph::layout_with_fr` if you want to define this yourself simply pass `x` and `y` position to `sg_nodes`.

For instance:

```r
N <- 5L
nodes <- sg_make_nodes(N)
nodes$x <- 1:N
nodes$y <- 1:N

sigmajs() %>% sg_nodes(nodes, id, size, color, x, y)
```

**Comment by shashj** [comment]
Cool will try it out

**Comment by JohnCoene** [comment]
I'll close that assuming this answered your quesiton.
