### ISSUE TITLE
Setting node attributes

### ISSUE THREAD

**Issue by SaharanAbhishek** [JohnCoene/sigmajs#15]
How can I assign each node a unique label of my choice and unique x and y coordinates. Means creating a number of node objects and pushing same to nodes list.

Same I am able to do in javascript..... 
g.nodes.push({
				id: data.nodes[i].id,
				label: labelName,
				x: xAxisVal,
				y: yAxisVal,
				size: .1
				color: nodeColor,
			});

**Comment by JohnCoene** [comment]
This is all in the [Get Started guide](http://sigmajs.john-coene.com/articles/get_started).

```r
# generate data using convenience functions
nodes <- sg_make_nodes()
edges <- sg_make_edges(nodes)

sigmajs() %>%
  sg_nodes(nodes, id, size, color, x = x, y = y) %>%
  sg_edges(edges, id, source, target)
```

**Comment by SaharanAbhishek** [comment]
Suppose I have below dataframe for nodes:

Node ID	xAxis yAxis Name	City
1	0	10	20	John	New York
2	1	11	21	Peter	Paris
3	2	12	22	Tom	        London
4	3	13	23	Sam	        Los Angeles
5	4	14	24	Jack	        Tokyo

for edges

Edge Source Target
1	0	1
2	0	3
3	1	4
4	1	2
5	2	3
6	3	1
7	4	4

In javascript case (I have JSON instead of dataframe in this case), first I will loop through all nodes and create object for each node with attribute and then push same to nodes array, same for edges.

Now want to achive same through R.

Thanks for quick response.

**Comment by JohnCoene** [comment]
Hi Saharan,

You do so with the snippet of code I shared.

```r
# generate data using convenience functions
nodes <- sg_make_nodes()
edges <- sg_make_edges(nodes)

sigmajs() %>%
  sg_nodes(nodes, id, size, color, x = x, y = y) %>%
  sg_edges(edges, id, source, target)
```

There is no need to explicitly loop over the `data.frame`. Is there a reason you want to add those nodes and edges one by one?

**Comment by SaharanAbhishek** [comment]
Thanks a lot, was not aware how to use data frame, just started with R.

One more thing, I am able to draw graph now, but unable to change edge color, its taking default node color.

Have tried defaultEdgeColor in sg_settings but didn't worked.

**Comment by SaharanAbhishek** [comment]
Just like each node have size, color options:
eg: sg_nodes(nodes, id, **size**, **color**)

can we have same for each edge:
eg: sg_edges(edges, id, source, target)

**Comment by JohnCoene** [comment]
You will find this in this part of the [official documentation](https://github.com/jacomyal/sigma.js/wiki/Settings)

You need 

```r
    nodes <- sg_make_nodes() 
    edges <- sg_make_edges(nodes) 
     
    sigmajs() %>% 
      sg_nodes(nodes, id, size, color) %>% 
      sg_edges(edges, id, source, target) %>% 
      sg_settings(edgeColor = "default", defaultEdgeColor = "red") 
```

You can change `edgeColor` to `source` or `target`. For the edge size, pass `size` like you do for nodes

**Comment by SaharanAbhishek** [comment]
Thanks for the help.

Now I am getting below console error:

**Uncaught The edge source must have an existing node id.**       sigma.min.js:2

Its related to the edges I am using, Have checked all edges manually they are fine, corresponds to valid Node ID, but still getting error, not sure why.

Please let me know if you have any idea regarding this.

Thanks in advance.

**Comment by SaharanAbhishek** [comment]
Thanks for the help :)

**Comment by SaharanAbhishek** [comment]
Sorry again distrubing you... 

Now getting issue in rendering images on web page... below code is working fine when running through **"Run App"** in RStudio.... but images does not rendered when using Rscript through terminal **"Rscript app.R"**.

**tabPanel(
img(
        src = "logo.png",        
        align = "center",
        height="50%", 
        width="50%"
      )
),**

**Comment by JohnCoene** [comment]
Where is `logo.png` located?

**Comment by SaharanAbhishek** [comment]
> Where is `logo.png` located?

In **www** folder and **.R** file is just outside that folder

**Comment by JohnCoene** [comment]
I think RStudio manages this for you, used outside of RStudio you must specify the asset location explicitly at the top of your `.R` file (before ui and server).

```r
library(shiny)
addResourcePath("www", "www")
```

Then change `logo.png` to `www/logo.png`, see `?addResourcePath` for more details.

**Comment by SaharanAbhishek** [comment]
it worked... thanks again for quick response :)
