### ISSUE TITLE
[JOSS-review] Add content to License file

### ISSUE THREAD

**Issue by strengejacke** [JohnCoene/sigmajs#2]
Hi John,
this issue is related to https://github.com/openjournals/joss-reviews/issues/814.
The JOSS requires the content of a license to be included in the license file. Please add the full license text to your existing LICENSE file. 

If this conflicts with a possible CRAN submission, add your license information for CRAN to the DESCRIPTION file (and probably exclude your LICENSE file from checks / package-building).

**Comment by JohnCoene** [comment]
I have used the [License content from the original sigma.js library](https://github.com/jacomyal/sigma.js/blob/master/LICENSE.txt) (MIT) as it should follow the same licensing.
