### ISSUE TITLE
Providing each node and edge with a specific colour via hex codes

### ISSUE THREAD

**Issue by jwscot** [JohnCoene/sigmajs#23]
Hi John,

Is it possible to provide each node and edge with a specific colour via hex codes?

Cheers,

Jamie

**Comment by JohnCoene** [comment]
Yes it's shown here:. https://sigmajs.john-coene.com/reference/graph.html

**Comment by jwscot** [comment]
Apologies but does that not only provide a way to give all nodes the same colour? I'd like to give each node a unique colour.

**Comment by JohnCoene** [comment]
Yes, in the examples.

```r
nodes <- sg_make_nodes()
edges <- sg_make_edges(nodes)

sg <- sigmajs() %>%
  sg_nodes(nodes, id, label, size, color) %>%
  sg_edges(edges, id, source, target)
```

**Comment by jwscot** [comment]
Ok, thanks.
