### ISSUE TITLE
Click events

### ISSUE THREAD

**Issue by jwscot** [JohnCoene/sigmajs#24]
Is there any additional info on click events online? I have read the CRAN page (https://cran.r-project.org/web/packages/sigmajs/sigmajs.pdf) and followed the link for the official documentation (https://github.com/jacomyal/sigma.js/wiki/Events-API)  but I don't find it clear. 

I would like to highlight the adjacent nodes, and the adjacent nodes of these, i.e. I would like to highlight a path through a tripartite graph.

**Comment by JohnCoene** [comment]
[like this?](https://sigmajs.john-coene.com/reference/neighbours.html)

**Comment by jwscot** [comment]
Unfortunately not, essentially I would like to highlight nodes that are related to each other through my own custom definition. 

I.e. 

for node in graph:
      create array of nodes in same family
      highlight these nodes only 



![Screenshot 2021-10-08 at 17 31 50](https://user-images.githubusercontent.com/78442777/136591892-f4e3fc6c-0100-4893-ae2b-641713e76d34.png)
.

**Comment by jwscot** [comment]
Where the orange edges are those that are highlighted

**Comment by JohnCoene** [comment]
That's currently not possible, I could expose the interface to enable it but it would be serious JavaScript work on your end to handle this correctly: it's not as easy as it seems. Maybe easier is via Shiny if you look at the demo and docs?
