### ISSUE TITLE
Exporting a dynamic graph

### ISSUE THREAD

**Issue by LuigiC72** [JohnCoene/sigmajs#28]
I was wondering if it is possible to export a dynamic network (while keeping the "dynamism" of the network) via the sg_export function or anything similar. Thanks!
Luigi

**Comment by JohnCoene** [comment]
Yes you can, with `saveWidget`

https://rdrr.io/cran/htmlwidgets/man/saveWidget.html

**Comment by LuigiC72** [comment]
Thanks! Done it
