### ISSUE TITLE
[JOSS-review] statement of need

### ISSUE THREAD

**Issue by strengejacke** [JohnCoene/sigmajs#3]
Related to https://github.com/openjournals/joss-reviews/issues/814

The README file contains a paragraph on the "statement of need", which describes very well who may benefit from this package.

Please revise the introduction of your paper and add a similar statement of need to it, as the summary paragraph does not fully satisfy the requirements for the statement of need. This is just a minor issue, you may copy from your readme.

One addition to the readme-file. You write

> sigmajs leverages the original library's great many methods

This is unclear to user who are not familiar with sigma.js, as it's not clear what the "original libraries" are. Please add a small sentence, which explains what the original library does and why there's an R implementation. **Edit:** _There's a good example in your paper. Maybe you should add some parts from the paper to the readme and vice versa._

**Comment by JohnCoene** [comment]
I think I have remedied to the above but somewhat unsure if I did it properly.

**Comment by jankatins** [comment]
I second this. 

Coming from igraph, I would have also liked to see what the benefit of this library is over igraph (interactivity?)

**Comment by strengejacke** [comment]
> I think I have remedied to the above but somewhat unsure if I did it properly.

I would also add a stronger statement of need to the README file - you can copy from your _paper.md_. Then I personally would close this issue.

**Comment by JohnCoene** [comment]
Thank you @strengejacke, I have added the statement of need from the paper to the README: https://github.com/JohnCoene/sigmajs/commit/550e5809da3973100f3d10a80edb6f85866445c2
