### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by erzk** [JohnCoene/sigmajs#7]
Thanks for this great package. I managed to run the example in `sg_nodes` but I'm a bit lost when I try to use my own data.
Can you improve the documentation to clarify what input is needed and what are the arguments?
Current description of the arguments is a bit sparse:
```
sg	An object of class sigmajsas intatiated by sigmajs.
data	Data.frame (or list) of nodes or edges.
...	any column.
```

Thanks

**Comment by JohnCoene** [comment]
Hi @erzk, thanks for pointing that out, this poor documentation to say the least, apologies. I focused on the [website](http://sigmajs.john-coene.com/) and as a result neglected roxygen2 comments. I will improve that for future realeases. In the meantime, you will find a  much better explanation in the [Get Started section](http://sigmajs.john-coene.com/articles/get_started.html).

**Comment by JohnCoene** [comment]
Information added in the `details` section in the dev version, will be pushed to CRAN soon.
