### ISSUE TITLE
crosstalk not working properly

### ISSUE THREAD

**Issue by brucefeiwang** [JohnCoene/sigmajs#8]
When clicking on the graph, table show different items.  this also happens on the demo.

**Comment by JohnCoene** [comment]
Yes, indeed. I will look into that. Thank you for reporting it.

**Comment by agoutsmedt** [comment]
I post here a problem that could be linked with the one above. 
I am using crosstalk with sigmajs and DT, using SharedData function. It works for creating an interactive graph with sigmajs. It works for the data table with DT. But the two are not linked together. When clicking on any line in the table, it is not selecting any corresponding node in the graph. When clicking on a node in the graph, it is said in the data table that there is no matched value. 
I have added a filtering bar, which is working with the data table, but not with the graph. 

[Here](https://mega.nz/file/LThHBY5D#jbs05c0Ng3N9oyoeQ6UUCBXFAZ5l_N4yRVo1tIJjfV0) is the .html illustration. [Here](https://mega.nz/file/aSwnWChZ#fOmyR-Hj9ZdR-gYuEnMnK-TDQydBEbvAIjO2O6P9zBc) are the data. 

My code is the following:
`library(crosstalk)
library(sigmajs)
library(DT)
library(htmltools)

nodes <- readRDS("~/macro_AA/nodes.RDS") #use the data here
edges <- readRDS("~/macro_AA/edges.RDS") #use the data here

# pass node ids as keys
sd <- SharedData$new(nodes, key = nodes$id)

div(
  filter_slider("nb_cit", "Citations", sd, column=~nb_cit, step=1, width=250),
  class = "raw",
  div(
    class = "raw-md-6",
    sigmajs() %>% # initialise
      sg_nodes(sd, id, label, size, color, x, y) %>% # add nodes
      sg_edges(edges, id, size, source, target) %>% # add edges
      sg_settings(drawLabels = TRUE, drawEdgeLabels = FALSE, 
                 defaultEdgeType = "curve", minNodeSize = 0.01, maxNodeSize = 10, 
                  minEdgeSize = 0.05, maxEdgeSize = 0.2, labelSize = "proportional",
                 borderSize = 0.5)
      #sg_neighbors()
  ),
  div(
    class = "raw-md-6",
     datatable(sd, extensions="Scroller", style="bootstrap", class="compact", width="100%",
    filter = "top", options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
  )
)`
